### ISSUE TITLE
change to h2, dont use h4 only cause its a smaller font size

### ISSUE THREAD

**Issue by Tolga1999** [SanHont/the-client-case#5]
https://github.com/SanHont/the-client-case/blob/a9f06be1fac65c161a63c06cc9cbc0aa16909512/afbeelding.html#L68

https://www.searchenginejournal.com/on-page-seo/header-tags/

![image](https://user-images.githubusercontent.com/112855878/193235812-1f36076c-3806-4f69-b5cd-55413fe6afbc.png)

**Comment by SanHont** [comment]
Changed it, thank you for the feedback and the information about the H1-6 tags.
